### ISSUE TITLE
Liens vers les référentiels obsolètes

### ISSUE THREAD

**Issue by sbonaventure** [emma11y/accessibilityCon2020#1]
Bonjour Emmanuelle,

Je préfère te faire une issue ici plutôt qu'une réponse via twitter, mais dans ta slide 36 tu fait référence aux référentiels qui ne sont plus en vigueur (RGAA3 et WCAG2.0). D'ailleurs le lien vers http://references.modernisation.gouv.fr/rgaa-accessibilite/ est une page 404.

**Comment by emma11y** [comment]
Bonjour Simon, 

Merci @sbonaventure pour ton commentaire. Il y a une semaine ou deux quand j'ai préparé cette présentation, le lien marchait. ;)
J'ai corrigé le lien. 

Merci beaucoup pour ta vigilance.
